name: conda_env_cdm_test
channels:
  - conda-forge
dependencies:
   - python == 3.9
   - pip==24.0
   - pip:
       - git+https://github.com/clinical-data-mining/msk_cdm.git
       - git+https://github.com/clinical-data-mining/cdm-cbioportal-etl.git
       - git+https://github.com/clinical-data-mining/cdm-comorbidities-disparities.git
       - git+https://github.com/clinical-data-mining/diagnosis_event_abstraction_icd.git
       - git+https://github.com/clinical-data-mining/cdm_metbert.git
       - git+https://github.com/clinical-data-mining/cdm-performance-status.git
       - git+https://github.com/clinical-data-mining/cdm-treatments.git
       - git+https://github.com/clinical-data-mining/radiology_report_segmentation.git
       - git+https://github.com/clinical-data-mining/pathology_report_segmentation.git
