name: msk_cdm
channels:
  - conda-forge
dependencies:
   - python == 3.12
   - pip:
       - minio==7.2.7, <8,
       - pydantic==2.3, <3,
       - conda-build==3.21.6,
       - boto3==1.35.5,
       - python-dotenv==1.0, <2,
       - pyarrow==14.0.2,
       - databricks-connect==14.3.2,
       - databricks-sql-connector==3.1.2,
       - databricks-sdk==0.28.0,
       - certifi==2024.2.2,
       - pandas==2.2.2,
       - scikit-learn==1.5.1,
       - mkdocstrings==0.21.2,
       - mkdocs==1.6.0,
       - mkdocs-material==9.1.7,
       - sqlite==3.45.3,
       - accelerate==0.27.2,
       - black==24.8.0,
       - cudatoolkit==11.1.74,
       - dataclasses==0.8,
       - delta-spark==3.0.0,
       - ipykernel==6.29.3,
       - matplotlib==3.8.3,
       - poetry==1.6.0,
       - seaborn==0.13.2,
       - pytest==7.2.2,
       - tox==3.26.0
       - git+https://github.com/clinical-data-mining/msk_cdm.git

